export const uniOfAdvStudies = [
	'',
	'Simonyi Károly Szakkollégium',
	'Batthyány Lajos Szakkollégium',
	'Bercsényi Építész Szakkollégium',
	'Biztonságpolitikai Szakkollégium',
	'BME Építész Klub',
	'BME Management Szakkollégium',
	'BME Szent-Györgyi Albert Szakkollégium',
	'BME Wigner Jenő Szakkollégium',
	'BME Zielinski Szilárd Építőmérnöki Szakkollégium',
	'Deák Tibor Szakkollégium',
	'Debreceni Egyetem Hatvani István Szakkollégium',
	'Debreceni Egyetem Kerpely Kálmán Szakkollégium',
	'Debreceni Szent László Katolikus Szakkollégium',
	'Don Bosco Szakkollégium',
	'ELTE Angelusz Róbert Társadalomtudományi Szakkollégium',
	'ELTE Bibó István Szakkollégium',
	'ELTE Illyés Sándor Szakkollégium',
	'Energetikai Szakkollégium',
	'Eötvös József Collegium',
	'EVK Szakkollégium',
	'Fiatal Autonóm Közgazdászok Társasága Szakkollégium',
	'Gépész Szakkollégium',
	'Gidai Erzsébet Közgazdaságtudományi Szakkollégium',
	'Gyakorlati Diplomácia Szakkollégiuma',
	'Hantos Elemér Szakkollégium',
	'Heller Farkas Szakkollégium',
	'Ihrig Károly Szsakkollégium',
	'Janus Pannonius Közgazdasági Szakkollégium',
	'Jedlik Ányos Szakkollégium',
	'Joghallgatók Önképző Szervezete',
	'Karolina Katolikus Egyetemi Szakkollégium',
	'Kaszap István Szakkollégium',
	'Kautz Gyula Közgazdász Szakkollégium',
	'Kepes György Szakkollégium',
	'Kerényi Károly Szakkollégium',
	'KommON BME Kommunikációs Szakkollégium',
	'Külker Szakkollégium',
	'Liska Tibor Szakkollégium',
	'Magyary Zoltán Szakkollégium',
	'Mikó Imre Jog- és Közgazdaságtudományi Szakkollégium',
	'Ostrakon Szakkollégium',
	'Pécsi Tudományegyetem Bölcsészettudományi Kar Wlislocki Henrik Szakkollégium',
	'Pécsi Tudományegyetem Műszaki és Informatikai Kar–Művészeti Kar B2 Transzdiszciplináris Szakkollégium',
	'Protestáns Felsőoktatási Szakkollégium',
	'Rajk László Szakkollégium',
	'Széchenyi István Szakkollégium',
	'Szegedi Keresztény Roma Szakkollégium',
	'Szegedi Tudományegyetem Eötvös Loránd Kollégium',
	'Szent György Szakkollégium',
	'Szent Ignác Jezsuita Szakkollégium',
	'SZTE Móra Ferenc Szakkollégium',
	'Társadalomelméleti Kollégium',
	'Tormay Béla Szakkollégium',
	'Zsuffa István Szakkollégium',
	'Nincs',
	'Egyéb',
];
